export const privacyTelemetryStatusCopy = {
  en: {
    senderState: "Sender",
    sender: { idle: "Idle", busy: "One attempt is running" },
    enrollment: {
      not_attempted: "Not attempted",
      waiting_retry: "Waiting for the next attempt",
      failed: "Enrollment failed",
      enrolled: "Enrolled",
    },
    lastEnrollmentAttempt: "Last enrollment attempt",
    lastEnrollmentResult: "Enrollment result",
    nextEnrollmentRetry: "Next enrollment retry",
    enrollmentSucceeded: "Enrollment confirmed",
    lastDeliveryAttempt: "Last delivery attempt",
    notAttempted: "Not attempted",
    notScheduled: "Not scheduled",
    lastError: "Last error",
    error: {
      network_error: "Service unavailable over the network",
      http_400: "Service rejected the request (400)",
      http_401: "Service rejected authorization (401)",
      http_403: "Service forbade the request (403)",
      http_409: "Service reported a conflict (409)",
      http_429: "Service temporarily rate limited requests (429)",
      http_5xx: "Temporary service error",
      unsupported_contract: "The service does not support this telemetry contract",
      invalid_response: "The service returned an invalid response",
      service_disabled: "Collection is temporarily disabled by the operator",
      authentication_rejected: "The saved enrollment was rejected",
      unknown: "Unknown bounded error",
    },
    queueDeliveryDistinction: "Queued means stored locally only. Delivery requires a service acknowledgment and queue removal.",
    refreshEventNote: "A successful refresh can enqueue up to three technical events: dashboard, page, and startup.",
    checkAndSend: "Check connection and send now",
    checking: "Checking connection…",
    checkStarted: "One background enrollment/send attempt started. Status refreshes automatically.",
    checkUnavailable: "Requires an enabled purpose, no pending deletion, and an idle sender.",
    checkResult: {
      manual_send_disabled: "Enable at least one telemetry purpose first.",
      manual_send_unavailable: "The background attempt could not start.",
      deletion_pending: "Wait for deletion confirmation first.",
      sender_busy: "One attempt is already running.",
      failed: "The connection check could not start.",
    },
  },
  ru: {
    senderState: "Отправитель",
    sender: { idle: "Ожидает", busy: "Выполняет одну попытку" },
    enrollment: {
      not_attempted: "Регистрация ещё не выполнялась",
      waiting_retry: "Ожидает следующей попытки",
      failed: "Регистрация не выполнена",
      enrolled: "Регистрация выполнена",
    },
    lastEnrollmentAttempt: "Последняя попытка регистрации",
    lastEnrollmentResult: "Результат регистрации",
    nextEnrollmentRetry: "Следующая попытка регистрации",
    enrollmentSucceeded: "Регистрация подтверждена",
    lastDeliveryAttempt: "Последняя попытка доставки",
    notAttempted: "Ещё не выполнялась",
    notScheduled: "Не запланирована",
    lastError: "Последняя ошибка",
    error: {
      network_error: "Сервис недоступен по сети",
      http_400: "Сервис отклонил запрос (400)",
      http_401: "Сервис отклонил авторизацию (401)",
      http_403: "Сервис запретил запрос (403)",
      http_409: "Сервис сообщил о конфликте (409)",
      http_429: "Сервис временно ограничил запросы (429)",
      http_5xx: "Временная ошибка сервиса",
      unsupported_contract: "Сервис не поддерживает этот telemetry contract",
      invalid_response: "Сервис вернул некорректный ответ",
      service_disabled: "Приём временно выключен оператором",
      authentication_rejected: "Сохранённая регистрация отклонена",
      unknown: "Неизвестная ограниченная ошибка",
    },
    queueDeliveryDistinction: "Очередь означает локальное хранение. Доставка требует подтверждения сервиса и удаления из очереди.",
    refreshEventNote: "Успешное обновление может добавить до трёх технических событий: dashboard, page и startup.",
    checkAndSend: "Проверить соединение и отправить сейчас",
    checking: "Проверяем соединение…",
    checkStarted: "Запущена одна фоновая попытка регистрации и отправки. Статус обновится автоматически.",
    checkUnavailable: "Нужны включённая цель, отсутствие ожидающего удаления и свободный отправитель.",
    checkResult: {
      manual_send_disabled: "Сначала включите хотя бы одну цель телеметрии.",
      manual_send_unavailable: "Не удалось запустить фоновую попытку.",
      deletion_pending: "Сначала дождитесь подтверждения удаления.",
      sender_busy: "Одна попытка уже выполняется.",
      failed: "Не удалось запустить проверку.",
    },
  },
} as const;

export type PrivacyTelemetryCopy = typeof privacyTelemetryStatusCopy.en;
